version: "3.8"

services:
  login-app:
    build: .
    restart: always
    environment:
      - FLASK_SECRET_KEY=${SECRET_KEY}
    networks:
      - traefik
    labels:
      # Configuraci贸n general
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"

      # Configuraci贸n HTTP
      - "traefik.http.routers.login-app-http.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.login-app-http.entrypoints=web"
      - "traefik.http.services.login-app.loadbalancer.server.port=5001"

      # Middleware para redirecci贸n a HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.login-app-http.middlewares=redirect-to-https@docker"

      # Configuraci贸n HTTPS
      - "traefik.http.routers.login-app-https.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.login-app-https.entrypoints=web-secure"
      - "traefik.http.routers.login-app-https.tls=true"
      - "traefik.http.routers.login-app-https.tls.certresolver=myhttpchallenge"

networks:
  traefik:
    external: true
